concerts/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

from .forms import LoginForm, RegisterForm
from .models import User
from . import db


bp = Blueprint("auth", __name__)


@bp.route("/account", methods=["GET", "POST"])
def account():
    """
    Renders the login page.
    """
    error = None
    loginform = LoginForm()

    if loginform.validate_on_submit():
        email = loginform.email.data
        password = loginform.password.data

        user = User.query.filter_by(email=email).first()

        if user is None:
            error = "Incorrect email"
        elif not check_password_hash(user.hash, password):
            error = "Incorrect password"

        if error is None:
            login_user(user)
        else:
            flash(error)

        return redirect(url_for("auth.account"))

    return render_template("pages/account.jinja", loginform=loginform)


@bp.route("/register", methods=["GET", "POST"])
def register():
    """
    Renders the register page.
    """
    error = None
    registerform = RegisterForm()

    if registerform.validate_on_submit():
        username = registerform.username.data
        email = registerform.email.data
        password = registerform.password.data
        contact = registerform.contact.data
        address = registerform.address.data

        if User.query.filter_by(username=username).first():
            error = "Username already exists"
        elif User.query.filter_by(email=email).first():
            error = "Email already exists"

        if error is None:
            hash = generate_password_hash(password)
            user = User(
                username=username,
                email=email,
                hash=hash,
                contact_number=contact,
                address=address,
            )

            db.session.add(user)
            db.session.commit()

            flash("Successfully registered")
            return redirect(url_for("auth.account"))
        else:
            flash(error)

        return redirect(url_for("auth.account"))

    return render_template("pages/register.jinja", registerform=registerform)


@bp.route("/logout")
@login_required
def logout():
    """
    Logs out the user and redirects to the account page.
    """
    logout_user()
    flash("Successfully logged out")
    return redirect(url_for("auth.account"))

concerts/views.py
from flask import Blueprint, render_template

mainbp = Blueprint("main", __name__)


@mainbp.route("/")
def index():
    return render_template("pages/home.jinja")

concerts/templates/pages/404.jinja
{% extends 'base.jinja' %}

{% block content %}
<div class="page container">
  <div class="d-flex justify-content-center my-5 mw-100">
    <h1 class="tx-400 text-center" style="font-size: 3rem;">
      404 - Page not found
    </h1>
  </div>

  <div class="row">
    <div class="d-flex justify-content-center my-3 mw-100">
      <p class="text-center" style="font-size: 1.5rem;">
        We can't seem to find the page you're looking for.
      </p>
    </div>
    <div class="d-flex justify-content-center mb-3 mw-100">
      <p class="text-center" style="font-size: 1.5rem;">
        If you entered the URL manually, try checking your spelling.
      </p>
    </div>
  </div>

  <div class="row">
    <div class="d-flex justify-content-center my-5">
      <a href="{{url_for('main.index')}}">
        <button type="button" name="button" class="btn btn-lg create-button bg-200 tx-000 mw-100">
          Return to home page
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock content %}

concerts/templates/pages/500.jinja
{% extends 'base.jinja' %}

{% block content %}
<div class="page container">
  <div class="d-flex justify-content-center my-5 mw-100">
    <h1 class="tx-400 text-center" style="font-size: 3rem;">
      500 - Internal Server Error
    </h1>
  </div>

  <div class="row">
    <div class="d-flex justify-content-center mb-3 mw-100">
      <p class="text-center" style="font-size: 1.5rem;">
        The server encountered an internal error or misconfiguration and was unable to complete your request.
      </p>
    </div>
    <div class="d-flex justify-content-center mb-3 mw-100">
      <p class="text-center" style="font-size: 1.5rem;">
        Try refreshing the page. Alternatively, contact the server administrator with anything you might have done that
        may have caused the error.
      </p>
    </div>
  </div>

  <div class="row">
    <div class="d-flex justify-content-center my-5">
      <a href="{{url_for('main.index')}}">
        <button type="button" name="button" class="btn btn-lg create-button bg-200 tx-000 mw-100">
          Back to home page
        </button>
      </a>
    </div>
  </div>
</div>
{% endblock content %}

concerts/templates/pages/account.jinja
{% extends "base.jinja" %}
{% from "_formhelpers.jinja" import render_field %}

{% block content %}
<div class="page container">
  <div class="container my-5">
    <div class="d-flex justify-content-center">
      <div class="card p-5 shadow bg-300 tx-000">
        {% if current_user.is_authenticated %}

        <div class="d-flex justify-content-center">
          <h2>Welcome, {{current_user.username}}</h2>
        </div>
        <div class="d-flex justify-content-center mt-4">
          <p>Would you like to log out?</p>
        </div>
        <div class="d-flex justify-content-center mt-3">
          <a href="{{ url_for('auth.logout') }}">
            <button type="button" class="btn bg-200 tx-000 login-button">
              Log out
            </button>
          </a>
        </div>

        {% else %}

        <div class="d-flex justify-content-center">
          <h2>Log in</h2>
        </div>
        <div class="d-flex justify-content-center mt-4">
          <form method="post">
            {{ loginform.csrf_token }}
            <div class="">
              {{ render_field(loginform.email, type="text", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(loginform.password, type="password", class="form-control") }}
            </div>

            <div class="d-flex justify-content-center mt-4">
              <button type="submit" class="btn bg-200 tx-000 login-button">
                Log in
              </button>
            </div>
          </form>
        </div>

        <div class="mt-4">
          <div class="d-flex justify-content-center">
            Don't have an account?
          </div>
          <div class="d-flex justify-content-center">
            Click&#160;<a href="{{url_for('auth.register')}}">Register</a>
          </div>
        </div>

        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

concerts/templates/pages/bookedevents.jinja
{% extends "base.jinja" %}

{% block content %}
<div class="page container">
  <div class="mt-3 d-flex justify-content-center">
    <h1 class="tx-400">Booked Events</h1>
  </div>

  <div class="row justify-content-center p-3">
    {% for index, booking in bookings %}
    <!-- bookedeventsrow -->
    {% include "./components/bookedeventsrow.jinja" %}
    {% endfor %}
  </div>
</div>
{% endblock content %}

concerts/templates/pages/eventdetails.jinja
{% extends "base.jinja" %}
{% from "_formhelpers.jinja" import render_field %}

{% block content %}
<div class="page container bg-400 tx-000">
  <!-- eventcontent -->
  {% include "./components/eventcontent.jinja" %}

  <!-- bookingmodal -->
  {% include "./components/bookingmodal.jinja" %}
</div>

{% endblock content %}

concerts/templates/pages/findevents.jinja
{% extends "base.jinja" %}

{% block content %}
<div class="page container">
  <div class="mt-3 d-flex justify-content-center">
    <h1 class="tx-400">Find Events</h1>
  </div>
  <div class="row justify-content-center p-3">
    <!-- eventfilters -->
    {% include "./components/eventfilters.jinja" %}

    <div class="col-lg-8">
      {% for index, event in events %}
      <!-- findeventsrow -->
      {% include "./components/findeventsrow.jinja" %}
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

concerts/templates/pages/home.jinja
{% extends "base.jinja" %}

{% block content %}
<div class="page default fluid-container bg-600">
  <div class="container home-page py-4 tx-000">
    <div class="row">
      <div class="d-flex justify-content-center my-5">
        <h1 class="text-center" style="font-size: 3rem;">
          Ever wanted to host a concert? Interested in attending one?
        </h1>
      </div>
    </div>
    <div class="row">
      <div class="d-flex justify-content-center my-3">
        <p class="text-center" style="font-size: 1.5rem;">
          You have come to the right place! Here, we make hosting concerts fast and easy
          so artists can focus on making the greatest performance!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="d-flex justify-content-center my-3">
        <p class="text-center" style="font-size: 1.5rem;">
          Sound interesting? Try browsing through our upcoming events!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="d-flex justify-content-center my-3">
        <a href="{{url_for('findevents.show')}}">
          <button type="button" name="button" class="btn bg-200 tx-000" style="font-size: 1rem; width: 15em;">
            Show me the events!
          </button>
        </a>
      </div>
    </div>
    <div class=" row my-3">
      <div class="d-flex justify-content-center">
        <p style="font-size: 1rem;">Already have an account?</p>
      </div>
      <div class="d-flex justify-content-center">
        <p style="font-size: 1rem;">
          Click&#160;<a href="{{url_for('auth.account')}}">here</a>&#160;to log
          in.
        </p>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

concerts/templates/pages/myevents.jinja
{% extends "base.jinja" %}

{% block content %}
<div class="page container">
  <div class="mt-3 d-flex justify-content-center">
    <h1 class="tx-400">My Events</h1>
  </div>
  <div class="row justify-content-center p-3">
    <div class="row nopadding mb-3 d-flex justify-content-center">
      <button class="btn bg-300 tx-000 btn-lg create-button nopadding shadow" type="button" data-bs-toggle="modal"
        data-bs-target="#event-editor-">
        Create event
      </button>
    </div>

    {% for index, event in events %}
    <!-- myeventsrow -->
    {% include "./components/myeventsrow.jinja" %}
    {% endfor %}
  </div>
</div>

{% set event = none %}
<!-- eventeditormodal -->
{% include "./components/eventeditormodal.jinja" %}
{% endblock content %}

concerts/templates/pages/register.jinja
{% extends "base.jinja" %}
{% from "_formhelpers.jinja" import render_field %}

{% block content %}
<div class="page container">
  <div class="container my-5">
    <div class="d-flex justify-content-center">
      <div class="card p-5 shadow bg-300 tx-000">
        <div class="d-flex justify-content-center">
          <h2>Register</h2>
        </div>
        <div class="d-flex justify-content-center mt-4">
          <form method="post">
            {{ registerform.csrf_token }}

            <div class="">
              {{ render_field(registerform.username, type="text", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(registerform.email, type="text", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(registerform.password, type="password", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(registerform.confirm, type="password", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(registerform.contact, type="text", class="form-control") }}
            </div>

            <div class="mt-3">
              {{ render_field(registerform.address, type="text", class="form-control") }}
            </div>

            <div class="d-flex justify-content-center mt-4">
              {{ render_field(registerform.submit, type="submit", class="btn bg-200 tx-000 login-button") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}